import type { Phone } from '@/lib/types';

const phones: Phone[] = [
  {
    id: 1,
    name: 'iPhone 7 Plus 128Go',
    brand: 'Apple',
    price: 114,
    originalPrice: 150,
    images: ['https://placehold.co/800x805.png', 'https://placehold.co/800x803.png'],
    description: 'L\'iPhone qui a tout changé avec son double appareil photo et son design emblématique.',
    features: ['Double appareil photo 12 Mpx', 'Puce A10 Fusion', 'Écran Retina HD'],
    specs: {
      display: '5.5" Retina HD',
      camera: 'Double 12MP (Grand-angle et Téléobjectif)',
      processor: 'Puce A10 Fusion',
      battery: 'Jusqu\'à 14 heures de lecture vidéo',
      storage: '128Go',
      os: 'iOS 15 compatible',
    },
    reviews: [
      { author: 'Client Satisfait', rating: 5, text: 'Un classique qui fonctionne toujours parfaitement.' },
    ],
  },
  {
    id: 2,
    name: 'iPhone 7 Plus 256Go',
    brand: 'Apple',
    price: 120,
    originalPrice: 180,
    images: ['https://placehold.co/800x802.png', 'https://placehold.co/800x804.png'],
    description: 'Plus d\'espace pour vos souvenirs avec le double appareil photo et la puissance de la puce A10 Fusion.',
    features: ['Double appareil photo 12 Mpx', 'Puce A10 Fusion', '256Go de stockage'],
    specs: {
      display: '5.5" Retina HD',
      camera: 'Double 12MP (Grand-angle et Téléobjectif)',
      processor: 'Puce A10 Fusion',
      battery: 'Jusqu\'à 14 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 15 compatible',
    },
    reviews: [
      { author: 'Super Utilisateur', rating: 5, text: 'Stockage immense, parfait pour mes besoins.' },
    ],
  },
   {
    id: 7,
    name: 'iPhone XR 64Go',
    brand: 'Apple',
    price: 165,
    originalPrice: 200,
    images: ['https://placehold.co/800x823.png', 'https://placehold.co/800x824.png'],
    description: 'Un écran Liquid Retina brillant. Face ID encore plus rapide. La puce la plus intelligente et la plus puissante dans un smartphone.',
    features: ['Face ID', 'Puce A12 Bionic', 'Design tout écran'],
    specs: {
      display: '6.1" Liquid Retina HD',
      camera: '12MP Large',
      processor: 'Puce A12 Bionic',
      battery: 'Jusqu\'à 16 heures de lecture vidéo',
      storage: '64Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Classique', rating: 4, text: 'Toujours un excellent téléphone pour les tâches quotidiennes.' },
    ],
  },
   {
    id: 11,
    name: 'iPhone XR 128Go',
    brand: 'Apple',
    price: 190,
    originalPrice: 230,
    images: ['https://placehold.co/800x825.png', 'https://placehold.co/800x826.png'],
    description: 'Un écran Liquid Retina brillant. Face ID encore plus rapide. Et plus d\'espace pour tout ce que vous aimez.',
    features: ['Face ID', 'Puce A12 Bionic', '128Go de stockage'],
    specs: {
      display: '6.1" Liquid Retina HD',
      camera: '12MP Large',
      processor: 'Puce A12 Bionic',
      battery: 'Jusqu\'à 16 heures de lecture vidéo',
      storage: '128Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Value King', rating: 5, text: 'Le meilleur rapport qualité-prix.' },
    ],
  },
  {
    id: 6,
    name: 'iPhone 11 64Go',
    brand: 'Apple',
    price: 214,
    originalPrice: 260,
    images: ['https://placehold.co/800x821.png', 'https://placehold.co/800x822.png'],
    description: 'Juste la bonne quantité de tout. Un nouveau système à double caméra qui capture plus de ce que vous voyez et aimez.',
    features: ['Puce A13 Bionic', 'Système à double caméra', 'Mode Nuit'],
    specs: {
      display: '6.1" Liquid Retina HD',
      camera: '12MP Principal, 12MP Ultra Large',
      processor: 'Puce A13 Bionic',
      battery: 'Jusqu\'à 17 heures de lecture vidéo',
      storage: '64Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'PhotographeAmateur', rating: 5, text: 'Le mode Nuit est fantastique.' },
    ],
  },
  {
    id: 12,
    name: 'iPhone 11 128Go',
    brand: 'Apple',
    price: 249,
    originalPrice: 280,
    images: ['https://placehold.co/800x827.png', 'https://placehold.co/800x828.png'],
    description: 'Juste la bonne quantité de tout, avec plus d\'espace. Un nouveau système à double caméra qui capture plus de ce que vous voyez et aimez.',
    features: ['Puce A13 Bionic', 'Système à double caméra', 'Mode Nuit'],
    specs: {
      display: '6.1" Liquid Retina HD',
      camera: '12MP Principal, 12MP Ultra Large',
      processor: 'Puce A13 Bionic',
      battery: 'Jusqu\'à 17 heures de lecture vidéo',
      storage: '128Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Super Content', rating: 5, text: 'L\'autonomie est excellente et les photos sont superbes.' },
    ],
  },
  {
    id: 13,
    name: 'iPhone 11 Pro 256Go',
    brand: 'Apple',
    price: 288,
    originalPrice: 330,
    images: ['https://placehold.co/800x830.png', 'https://placehold.co/800x831.png'],
    description: 'Un système à trois caméras transformateur qui ajoute des tonnes de capacités sans complexité.',
    features: ['Système à trois caméras Pro', 'Puce A13 Bionic', 'Écran Super Retina XDR'],
    specs: {
      display: '5.8" Super Retina XDR',
      camera: 'Triple 12MP (Ultra large, Grand-angle, Téléobjectif)',
      processor: 'Puce A13 Bionic',
      battery: 'Jusqu\'à 18 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Pro User', rating: 5, text: 'Les caméras sont incroyables !' },
    ],
  },
  {
    id: 14,
    name: 'iPhone 11 Pro Max 256Go',
    brand: 'Apple',
    price: 350,
    originalPrice: 400,
    images: ['https://placehold.co/800x832.png', 'https://placehold.co/800x833.png'],
    description: 'Le premier système à trois caméras à combiner une technologie de pointe avec la simplicité légendaire de l\'iPhone. Sur un grand écran.',
    features: ['Système à trois caméras Pro', 'Puce A13 Bionic', 'Écran Super Retina XDR 6.5 pouces'],
    specs: {
      display: '6.5" Super Retina XDR',
      camera: 'Triple 12MP (Ultra large, Grand-angle, Téléobjectif)',
      processor: 'Puce A13 Bionic',
      battery: 'Jusqu\'à 20 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Max Power', rating: 5, text: 'Le meilleur grand iPhone.' },
    ],
  },
  {
    id: 15,
    name: 'iPhone 12 Pro 256Go',
    brand: 'Apple',
    price: 378,
    originalPrice: 430,
    images: ['https://placehold.co/800x834.png', 'https://placehold.co/800x835.png'],
    description: 'Un bond en avant. 5G. Puce A14 Bionic, la plus rapide sur smartphone. Système de caméra Pro pour des photos incroyables en basse lumière.',
    features: ['5G', 'Puce A14 Bionic', 'Scanner LiDAR'],
    specs: {
      display: '6.1" Super Retina XDR',
      camera: 'Système de caméra Pro 12MP (Ultra large, Grand-angle, Téléobjectif)',
      processor: 'Puce A14 Bionic',
      battery: 'Jusqu\'à 17 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Early Adopter', rating: 5, text: 'Le design est magnifique et la 5G est rapide.' },
    ],
  },
  {
    id: 16,
    name: 'iPhone 12 Pro Max 256Go',
    brand: 'Apple',
    price: 485,
    originalPrice: 530,
    images: ['https://placehold.co/800x836.png', 'https://placehold.co/800x837.png'],
    description: 'Le système de caméra Pro sur iPhone passe au Max. Un plus grand écran Super Retina XDR de 6,7 pouces.',
    features: ['5G', 'Puce A14 Bionic', 'Scanner LiDAR', 'Plus grand écran'],
    specs: {
      display: '6.7" Super Retina XDR',
      camera: 'Système de caméra Pro 12MP (Ultra large, Grand-angle, Téléobjectif)',
      processor: 'Puce A14 Bionic',
      battery: 'Jusqu\'à 20 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Gamer Mobile', rating: 5, text: 'L\'écran est parfait pour les jeux et les films.' },
    ],
  },
  {
    id: 4,
    name: 'iPhone 13 128Go',
    brand: 'Apple',
    price: 368,
    originalPrice: 470,
    images: ['https://placehold.co/800x817.png', 'https://placehold.co/800x818.png'],
    description: 'Votre nouveau superpouvoir. Notre système à double caméra le plus avancé à ce jour. Une puce qui laisse la concurrence sur place.',
    features: ['Puce A15 Bionic', 'Mode Cinématique', 'Bouclier en céramique'],
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '12MP Principal, 12MP Ultra Large',
      processor: 'Puce A15 Bionic',
      battery: 'Jusqu\'à 19 heures de lecture vidéo',
      storage: '128Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'BonAchat', rating: 5, text: 'Une valeur sûre pour le prix.' },
    ],
  },
   {
    id: 17,
    name: 'iPhone 13 256Go',
    brand: 'Apple',
    price: 400,
    originalPrice: 500,
    images: ['https://placehold.co/800x819.png', 'https://placehold.co/800x820.png'],
    description: 'Votre nouveau superpouvoir. Avec deux fois plus d\'espace pour tout ce que vous aimez.',
    features: ['Puce A15 Bionic', 'Mode Cinématique', '256Go de stockage'],
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '12MP Principal, 12MP Ultra Large',
      processor: 'Puce A15 Bionic',
      battery: 'Jusqu\'à 19 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'StockageMax', rating: 5, text: 'Enfin assez de place !' },
    ],
  },
  {
    id: 18,
    name: 'iPhone 13 Pro 128Go',
    brand: 'Apple',
    price: 445,
    originalPrice: 500,
    images: ['https://placehold.co/800x840.png', 'https://placehold.co/800x841.png'],
    description: 'Oh. Tellement. Pro. Un système de caméra radicalement plus puissant. Un écran si réactif que chaque interaction semble nouvelle.',
    features: ['ProMotion', 'Puce A15 Bionic', 'Système de caméra Pro'],
    specs: {
      display: '6.1" Super Retina XDR avec ProMotion',
      camera: 'Système de caméra Pro 12MP (Téléobjectif, Grand-angle, Ultra large)',
      processor: 'Puce A15 Bionic',
      battery: 'Jusqu\'à 22 heures de lecture vidéo',
      storage: '128Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Créateur de contenu', rating: 5, text: 'L\'écran ProMotion est un game-changer.' },
    ],
  },
   {
    id: 19,
    name: 'iPhone 13 Pro 256Go',
    brand: 'Apple',
    price: 488,
    originalPrice: 550,
    images: ['https://placehold.co/800x842.png', 'https://placehold.co/800x843.png'],
    description: 'Oh. Tellement. Pro. Avec plus d\'espace de stockage pour vos créations.',
    features: ['ProMotion', 'Puce A15 Bionic', 'Système de caméra Pro', '256Go de stockage'],
    specs: {
      display: '6.1" Super Retina XDR avec ProMotion',
      camera: 'Système de caméra Pro 12MP (Téléobjectif, Grand-angle, Ultra large)',
      processor: 'Puce A15 Bionic',
      battery: 'Jusqu\'à 22 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Photographe Pro', rating: 5, text: 'Les photos sont incroyables et j\'ai de la place pour toutes.' },
    ],
  },
  {
    id: 20,
    name: 'iPhone 13 Pro Max 128Go',
    brand: 'Apple',
    price: 550,
    originalPrice: 600,
    images: ['https://placehold.co/800x844.png', 'https://placehold.co/800x845.png'],
    description: 'Le plus grand bond en avant du système de caméra Pro. Un écran Super Retina XDR avec ProMotion. Une autonomie exceptionnelle.',
    features: ['ProMotion', 'Puce A15 Bionic', 'La meilleure autonomie sur iPhone'],
    specs: {
      display: '6.7" Super Retina XDR avec ProMotion',
      camera: 'Système de caméra Pro 12MP (Téléobjectif, Grand-angle, Ultra large)',
      processor: 'Puce A15 Bionic',
      battery: 'Jusqu\'à 28 heures de lecture vidéo',
      storage: '128Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Utilisateur intensif', rating: 5, text: 'La batterie dure une éternité !' },
    ],
  },
   {
    id: 21,
    name: 'iPhone 13 Pro Max 256Go',
    brand: 'Apple',
    price: 600,
    originalPrice: 750,
    images: ['https://placehold.co/800x846.png', 'https://placehold.co/800x847.png'],
    description: 'Le plus grand bond en avant du système de caméra Pro. Et un espace de stockage énorme.',
    features: ['ProMotion', 'Puce A15 Bionic', 'La meilleure autonomie sur iPhone', '256Go de stockage'],
    specs: {
      display: '6.7" Super Retina XDR avec ProMotion',
      camera: 'Système de caméra Pro 12MP (Téléobjectif, Grand-angle, Ultra large)',
      processor: 'Puce A15 Bionic',
      battery: 'Jusqu\'à 28 heures de lecture vidéo',
      storage: '256Go',
      os: 'iOS 17 compatible',
    },
    reviews: [
      { author: 'Vidéaste', rating: 5, text: 'Parfait pour filmer en ProRes.' },
    ],
  },
];

export function getPhones() {
  return phones;
}

export function getPhoneById(id: number) {
  return phones.find((phone) => phone.id === id);
}

export function getPhoneBrands() {
    const brands = phones.map(phone => phone.brand);
    return [...new Set(brands)];
}
